/* components.h */

#include <stdio.h>


#define MINIMO_VALOR_RESISTENCIA 0
#define MAXIMO_VALOR_RESISTENCIA 10000

#define MINIMO_VALOR_FACTOR_CALIDAD 0
#define MAXIMO_VALOR_FACTOR_CALIDAD 10

#define MINIMO_VALOR_FRECUENCIA 10
#define MAXIMO_VALOR_FRECUENCIA 50000

#define MULTIPLICADOR_RESISTENCIA 1000
#define MULTIPLICADOR_CAPACITOR 1000000000

#define UNIDAD_CAPACITOR "nF"
#define UNIDAD_FRECUENCIA "Hz"
#define UNIDAD_RESISTOR "Ohm"
#define UNIDAD_INDUCTOR "H"

#define M_PI 3.1415


#define MAX_STR 100
